// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolYCNrOB8ot75VmtreypUknrzn88lyAE',
    appId: '1:29580782184:web:c51a5084a945047107e9dd',
    messagingSenderId: '29580782184',
    projectId: 'convenientmarketapp',
    authDomain: 'convenientmarketapp.firebaseapp.com',
    storageBucket: 'convenientmarketapp.firebasestorage.app',
    measurementId: 'G-PBTKCD00G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7xbufF2iN9gyflCO9WyNd2_WhgNcIG4',
    appId: '1:29580782184:android:0588593f2fadd29f07e9dd',
    messagingSenderId: '29580782184',
    projectId: 'convenientmarketapp',
    storageBucket: 'convenientmarketapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWB1QdzVzz_TlCBWggRuIrkFIJHUQxwg',
    appId: '1:29580782184:ios:30eca9fa864fd8c207e9dd',
    messagingSenderId: '29580782184',
    projectId: 'convenientmarketapp',
    storageBucket: 'convenientmarketapp.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWB1QdzVzz_TlCBWggRuIrkFIJHUQxwg',
    appId: '1:29580782184:ios:30eca9fa864fd8c207e9dd',
    messagingSenderId: '29580782184',
    projectId: 'convenientmarketapp',
    storageBucket: 'convenientmarketapp.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBolYCNrOB8ot75VmtreypUknrzn88lyAE',
    appId: '1:29580782184:web:a184ee1a83cd747907e9dd',
    messagingSenderId: '29580782184',
    projectId: 'convenientmarketapp',
    authDomain: 'convenientmarketapp.firebaseapp.com',
    storageBucket: 'convenientmarketapp.firebasestorage.app',
    measurementId: 'G-JDQY6LY0SN',
  );

}